// Generated by core/build.mjs from film.components. Edit the component files.
import type {ComponentType} from 'react';
import type {ShotProps} from './types';
import ContinuousExample from "./shots/ContinuousExample";
import KitShowcase from "./shots/KitShowcase";
import ProductShowcase from "./shots/ProductShowcase";

export const registry: Record<string,ComponentType<ShotProps>> = {"ContinuousExample": ContinuousExample,
"KitShowcase": KitShowcase,
"ProductShowcase": ProductShowcase,
};
